version: '3'

services:
  webrung_tests_service:
    environment:
      - PORT=8001
      - DB_DIALECT=sqlite3
      - DB_URL=/tmp/webrung.db
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/go/src/github.com/minhajuddinkhan/webrung/"
    ports:
      - "8001:8001"

  webrung_test_suite:
    environment:
      - PORT=8001
      - HOST=webrung_tests_service
    depends_on:
      - webrung_tests_service
    build:
      context: .
      dockerfile: Dockerfile-test
    volumes:
      - ".:/go/src/github.com/minhajuddinkhan/webrung/"
